import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import "@yundeving/story-book-demo-ui/style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex bg-default-200 dark:bg-default-800">
          <Sidebar />
          <div className="flex-1 overflow-auto p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
