import "@yundeving/story-book-demo-ui/style.css";

import type { Metadata } from "next";

import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="bg-default-200 dark:bg-default-800 min-h-screen">
            <Header />
            <div className="flex pt-16">
              {/* Header 높이만큼 padding-top */}
              <Sidebar />
              <div className="flex-1 overflow-auto p-6">{children}</div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
